export function convertCountries(c) {
  if (!c || c === 'nan') return "--"; // Handle empty, null, undefined, or string 'nan'

  const country_map = {
        'AFG': 'Afghanistan',
        'ALB': 'Albania',
        'ARE': 'United Arab Emirates',
        'ARG': 'Argentina',
        'ARM': 'Armenia',
        'ASM': 'American Samoa',
        'AUS': 'Australia',
        'AUT': 'Austria',
        'BEL': 'Belgium',
        'BGD': 'Bangladesh',
        'BGR': 'Bulgaria',
        'BHS': 'Bahamas',
        'BRA': 'Brazil',
        'BRB': 'Barbados',
        'CAN': 'Canada',
        'CHL': 'Chile',
        'COL': 'Colombia',
        'CRI': 'Costa Rica',
        'CYP': 'Cyprus',
        'CZE': 'Czech Republic',
        'DEU': 'Germany',
        'DNK': 'Denmark',
        'DOM': 'Dominican Republic',
        'DZA': 'Algeria',
        'ECU': 'Ecuador',
        'EGY': 'Egypt',
        'ESP': 'Spain',
        'EST': 'Estonia',
        'ETH': 'Ethiopia',
        'FIN': 'Finland',
        'FRA': 'France',
        'GBR': 'United Kingdom',
        'GHA': 'Ghana',
        'GMB': 'Gambia',
        'GRC': 'Greece',
        'GTM': 'Guatemala',
        'HKG': 'Hong Kong',
        'HRV': 'Croatia',
        'IDN': 'Indonesia',
        'IND': 'India',
        'IRL': 'Ireland',
        'IRQ': 'Iraq',
        'ISL': 'Iceland',
        'ISR': 'Israel',
        'ITA': 'Italy',
        'JAM': 'Jamaica',
        'JPN': 'Japan',
        'KAZ': 'Kazakhstan',
        'KEN': 'Kenya',
        'KNA': 'Saint Kitts and Nevis',
        'KOR': 'South Korea',
        'KWT': 'Kuwait',
        'LKA': 'Sri Lanka',
        'LTU': 'Lithuania',
        'LVA': 'Latvia',
        'MAC': 'Macao',
        'MAR': 'Morocco',
        'MDA': 'Moldova',
        'MEX': 'Mexico',
        'MKD': 'North Macedonia',
        'MLT': 'Malta',
        'MUS': 'Mauritius',
        'MYS': 'Malaysia',
        'NGA': 'Nigeria',
        'NIC': 'Nicaragua',
        'NLD': 'Netherlands',
        'NOR': 'Norway',
        'NPL': 'Nepal',
        'NZL': 'New Zealand',
        'PAK': 'Pakistan',
        'PER': 'Peru',
        'PHL': 'Philippines',
        'POL': 'Poland',
        'PRI': 'Puerto Rico',
        'PRT': 'Portugal',
        'ROU': 'Romania',
        'RUS': 'Russia',
        'SAU': 'Saudi Arabia',
        'SGP': 'Singapore',
        'SLV': 'El Salvador',
        'SRB': 'Serbia',
        'SUR': 'Suriname',
        'SVN': 'Slovenia',
        'SWE': 'Sweden',
        'TCA': 'Turks and Caicos Islands',
        'THA': 'Thailand',
        'TTO': 'Trinidad and Tobago',
        'TUN': 'Tunisia',
        'TUR': 'Turkey',
        'TWN': 'Taiwan',
        'UGA': 'Uganda',
        'UKR': 'Ukraine',
        'UMI': 'United States Minor Outlying Islands',
        'URY': 'Uruguay',
        'USA': 'United States',
        'VEN': 'Venezuela',
        'VIR': 'U.S. Virgin Islands',
        'VNM': 'Vietnam',
        'ZAF': 'South Africa',
        'ZMB': 'Zambia'
    };

    return country_map[c] || "--";
}
